# Log level can be one of: trace debug info warn error fatal panic
loglevel = "debug"

# API listen.
# The 'host' field can be IP or DNS name
# The 'prefix' part of URI in between host and the Domain Connect name
#     space, for example https://{host}/{prefix}/v2/{domain}/settings
[api]
    host = "127.0.0.1"
    port = 9270
    prefix = "/example"

# Prometheus metrics.
# The 'host' field can be IP or DNS name
[metrics]
    host = "127.0.0.1"
    port = 9271
    path = "/metrics"

# EOF
